// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrXbUACGPEHZ23oeWbOLIcoB-D4Ffm0vg',
    appId: '1:1035681477939:web:c4943be194718ca8303a46',
    messagingSenderId: '1035681477939',
    projectId: 'flutter-app-productos-21bac',
    authDomain: 'flutter-app-productos-21bac.firebaseapp.com',
    databaseURL: 'https://flutter-app-productos-21bac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-productos-21bac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_g-P6scFlWNXd814PJ8fmEv3Qf8ZkDhA',
    appId: '1:1035681477939:android:dfc4fb7e5827b4b5303a46',
    messagingSenderId: '1035681477939',
    projectId: 'flutter-app-productos-21bac',
    databaseURL: 'https://flutter-app-productos-21bac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-productos-21bac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy2ju5aRydygi3S8t1QBinezWzXeT7yzY',
    appId: '1:1035681477939:ios:bdf346acd4afcf0b303a46',
    messagingSenderId: '1035681477939',
    projectId: 'flutter-app-productos-21bac',
    databaseURL: 'https://flutter-app-productos-21bac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-productos-21bac.appspot.com',
    iosBundleId: 'com.example.productesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrXbUACGPEHZ23oeWbOLIcoB-D4Ffm0vg',
    appId: '1:1035681477939:web:91cc31e3366e52dd303a46',
    messagingSenderId: '1035681477939',
    projectId: 'flutter-app-productos-21bac',
    authDomain: 'flutter-app-productos-21bac.firebaseapp.com',
    databaseURL: 'https://flutter-app-productos-21bac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-productos-21bac.appspot.com',
  );
}
